- hosts: localhost
  become: yes
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: https://github.com/shawpooja17/Project_IGP/blob/main/deployment.yml
      dest: /root/
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /root/deployment.yml
    
   
