kind: Deployment
apiVersion: apps/v1
metadata:
    name: abctechnologies-deployment
spec:
    replicas: 2
    minReadySeconds: 35
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: abctechno
    template:
        metadata:
            labels:
                app: abctechno
        spec:
            containers:
                - image: poojashaw/tomcatwebserver
                  name: app
---

kind: Service
apiVersion: v1
metadata:
    name: abctechno-service
spec:
    type: NodePort
    selector:
        app: abctechno
    ports:
        - port: 80 #cluster port
          targetPort: 8080 #container image port
